### ISSUE TITLE
Lesson 4 - signed_tx code line is returning "binascii.Error: Non-hexadecimal digit found"

### ISSUE THREAD

**Issue by DorianDaSilva** [smartcontractkit/full-blockchain-solidity-course-py#1373]
Hi, 

code is printing fine up to this line, then i get this error.

I have been stuck on this for about 1 week now and noone seems to know the solution. I would appreciate the help.

**Below is the code:**

`from` solcx import compile_standard, install_solc
import json
from web3 import Web3
import os
from dotenv import load_dotenv

load_dotenv()

install_solc("0.6.0")

with open("./SimpleStorage.sol", "r") as file:
    simple_storage_file = file.read()
    # print(simple_storage_file)

compiled_sol = compile_standard(
    {
        "language": "Solidity",
        "sources": {"SimpleStorage.sol": {"content": simple_storage_file}},
        "settings": {
            "outputSelection": {
                "*": {"*": ["abi", "metadata", "evm.bytecode", "evm.sourceMap"]}
            },
        },
    },
    solc_version="0.6.0",
)
#print(compiled_sol)

with open("compiled_code.json", "w") as file:
    json.dump(compiled_sol, file)

bytecode = compiled_sol["contracts"]["SimpleStorage.sol"]["SimpleStorage"]["evm"][
    "bytecode"
]["object"]

abi = compiled_sol["contracts"]["SimpleStorage.sol"]["SimpleStorage"]["abi"]

w3 = Web3(Web3.HTTPProvider("http://127.0.0.1:7545"))
chain_id = 1337
my_address = "0xBb058FD53c96678a6E3b1dFa99907b631DddB608"
private_key = os.getenv("PRIVATE_KEY")
#print(private_key)

SimpleStorage = w3.eth.contract(abi=abi, bytecode=bytecode)
#print(SimpleStorage)

nonce = w3.eth.getTransactionCount(my_address)
#print(nonce)

transaction = SimpleStorage.constructor().buildTransaction(
    {
        "gasPrice": w3.eth.gas_price,
        "chain_Id": chain_id,
        "from": my_address,
        "nonce": nonce,
    }
)
#print(transaction)

signed_txn = w3.eth.account.sign_transaction(transaction, `private_key=private_key)`

**When I print this last line i get this result in the terminal (Note that One block was created on Ganache but never the transaction)**

C:\Users\doria\demos\web3_py_simple_storage> python deploy.py
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "C:\Users\doria\demos\web3_py_simple_storage\deploy.py", line 71, in <module>
    signed_txn = w3.eth.account.sign_transaction(transaction, private_key=private_key)
  File "C:\Users\doria\AppData\Roaming\Python\Python310\site-packages\eth_utils\decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "C:\Users\doria\AppData\Roaming\Python\Python310\site-packages\eth_account\account.py", line 743, in sign_transaction
    account = self.from_key(private_key)
  File "C:\Users\doria\AppData\Roaming\Python\Python310\site-packages\eth_utils\decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "C:\Users\doria\AppData\Roaming\Python\Python310\site-packages\eth_account\account.py", line 255, in from_key
    key = self._parsePrivateKey(private_key)
  File "C:\Users\doria\AppData\Roaming\Python\Python310\site-packages\eth_utils\decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "C:\Users\doria\AppData\Roaming\Python\Python310\site-packages\eth_account\account.py", line 793, in _parsePrivateKey     
    return self._keys.PrivateKey(HexBytes(key))
  File "C:\Users\doria\AppData\Roaming\Python\Python310\site-packages\hexbytes\main.py", line 23, in __new__
    bytesval = to_bytes(val)
  File "C:\Users\doria\AppData\Roaming\Python\Python310\site-packages\hexbytes\_utils.py", line 17, in to_bytes
    return hexstr_to_bytes(val)
  File "C:\Users\doria\AppData\Roaming\Python\Python310\site-packages\hexbytes\_utils.py", line 50, in hexstr_to_bytes
    return binascii.unhexlify(ascii_hex)
binascii.Error: Non-hexadecimal digit found

**Thank you!**

**Comment by HiDDehris** [comment]
Hi @DorianDaSilva ,

By looking at the error that you got, the issue seems happening in the process of retrieving your private_key. 
Since we should never share the PRIVATE_KEY, so just let's do few assumption.

In .env file,
1. Ensure your PRIVATE_KEY value starts with 0x 
2. Ensure you copy paste the complete value of your private key.

Hope this help

Best Regards.

**Comment by DorianDaSilva** [comment]
Hey @HiDDehris,

Thank you for the input. I have paste the entire key from ganache including 0x at the beginning several times, switched keys both in .env and windows PATH multiple times, changed the brackets several times and my understanding is that it is related to the Ganache RPC and the connection between vscode and ganache or most likely an issue with the compiler.

If it is the compiler the issue maybe solcx. It shows as installed on pwrshell but as missing extension on wsl. Maybe this is related. What do you think?

**Comment by DorianDaSilva** [comment]
UPDATE: I run the code using my visible private key instead of the .env file and the signture prints on terminal as long as I remove the "chain_id": chain_id line from transaction function as seen below:

`transaction = SimpleStorage.constructor().buildTransaction(
    {
        "gasPrice": w3.eth.gas_price,
        #"chain_id": chain_id,
        "from": my_address,
        "nonce": nonce,
    }
)
print(transaction)`

But as soon as I go back to using the environment variable i get the binascii.Error issue.

Seems the problem is with the .env file or the .gitignore

**Comment by DorianDaSilva** [comment]
Couldn't fix the problem with environment variable which is unfortunate because it is a necessity but managed to run and sign transactions when not using the .env file as below.

w3 = Web3(Web3.HTTPProvider("http://127.0.0.1:7545"))
chain_id = 1337
my_address = "0xBb058FD53c96678a6E3b1dFa99907b631DddB608"
#private_key = os.getenv("PRIVATE_KEY")
private_key = "0x499e57cc5e26f82aac28955b1de541bddfc10a3ef4d17c19d0c0aa81467935a2"
print(private_key)

SimpleStorage = w3.eth.contract(abi=abi, bytecode=bytecode)
#print(SimpleStorage)

nonce = w3.eth.getTransactionCount(my_address)
#print(nonce)

transaction = SimpleStorage.constructor().buildTransaction(
    {
        "gasPrice": w3.eth.gas_price,
        #"chain_id": chain_id,
        "from": my_address,
        "nonce": nonce,
    }
)
#print(transaction)

signed_txn = w3.eth.account.sign_transaction(transaction, private_key=private_key)
tx_hash = w3.eth.send_raw_transaction(signed_txn.rawTransaction)
tx_receipt = w3.eth.wait_for_transaction_receipt(tx_hash)
print(signed_txn)
`

would still very much appreciate a solution for the .env issue. Thank you

**Comment by HiDDehris** [comment]
TBH, since the transaction could be done when private_key exposed in deploy.py file, then should not be environment issue anymore. (But I am not 100% sure on this).

I have tried to run your codes and made some amendment, it works perfectly fine. Here are the changes:

1.
> compiled_sol = compile_standard(
> {
> "language": "Solidity",
> "sources": {"SimpleStorage.sol": {"content": simple_storage_file}},
> "settings": {
> "outputSelection": {
> "_": {"_": ["abi", "metadata", "evm.bytecode", "evm.sourceMap"]}
> },
> },
> },
> solc_version="0.6.0",
> )

"evm.sourceMap" => "evm.bptecode.sourceMap"

2. 

> w3 = Web3(Web3.HTTPProvider("http://127.0.0.1:7545"))
> chain_id = 1337
> my_address = "0xBb058FD53c96678a6E3b1dFa99907b631DddB608"
> private_key = os.getenv("PRIVATE_KEY")

chain_id => chainid &
instead of listening to 127.0.0.1:7545, I changed HostName to 172.31.48.1 - vEthernet (WSL) on Ganache UI. ( I was having issue to connect with 0.0.0.0 and 127.0.0.1 )

FYI, Private_key in .env file has no bracket
example: `export PRIVATE_KEY=0x28cb5832873f6a92ea9984b941deeecad1b5d7a5cffd005cfda3c23f252c202b`

and .gitignore file is just to ensure files listed in it will not get uploaded to github, so it shall not affect compile/run process.

**Comment by The-digitalhermes** [comment]
Not sure if this solution is correct but I removed the "0x" from the beginning of the private key in the .env file 

I did this because I counted 64 digits in the private key. But when you add the "0x" in the front of the private key it makes it 66 digits which is not a hexadecimal or factor of 16: 16, 32, 48, 64.

So after removing that "0x", I refreshed the page "Ctrl+Shift+P" and then "Ctrl+R"

Relaunched the terminal and ran the contract and it worked. 

Originally, that is the error code that I was getting:

"return binascii.unhexlify(ascii_hex)
binascii.Error: Non-hexadecimal digit found"

Strangely though, after making the change of removing the "0x", I put it back to see if I would get the same error and it still works. So not sure what happened but now it does work. 

Even reflects on Ganash transactions/blocks all the different times I changed it back and forth.

**Comment by DorianDaSilva** [comment]
@HiDDehris I appreciate the input, tried using your url for rpc connection but it produced a different error. In fact it returned an error even when the key was exposed. Maybe different systems?

Will move on with exposed key for now and hopefully environment variables in brownie won't be an issue.

@The-digitalhermes your solution actually worked for me. I was certain to have tried that solution but maybe I was missing an element when I initially tried. either way, thank you for the input and helping me solve this puzzle.
