### ISSUE TITLE
Lesson 7: abstract contract and override issue with VRFConsumerBase.sol

### ISSUE THREAD

**Issue by emilrueh** [smartcontractkit/full-blockchain-solidity-course-py#1792]
Around the 7h mark in the tutorial I have encountered a `Contract "Lottery" should be marked as abstract.` and a `Function has override specified but does not override anything.` issue.

After looking through multiple forums of people encountering similar issues no solution was helpful to my problem.

**Comment by emilrueh** [comment]
I realized it was an import issue or rather a version issue.
As soon as I changed the VRFConsumerBase import from:
`import "@chainlink/contracts/src/v0.6/VRFConsumerBase.sol";`
to:
`import "@chainlink/contracts/src/v0.7/VRFConsumerBase.sol";`
both issues resolved.

**Comment by cromewar** [comment]
Hello @emilrueh 
Well this tends to happen when your contract depends on imports which as well depends on other contracts, as they might and most probably will depend on different solidity versions is common to encounter this problems.

So, the question here is do we really need to update the solidity version?
Most of the cases the answer is no, newer solidity version have some changes yes, but not that significant and if the contracts you are going to import from rely on older versions is ok to use them.

Let's suppose you have some complex math on a contract with a version minor to 0.8, you might consider upgrading to 0.8 and above as since that version SafeMath is not needed anymore and you can manage your math equations better. But this is just a specific case, not something that you will actually have to dealt with.

Anyways as you are on lesson 7 @Neftyr just published an updated working version for VRF V2 you can check out: https://github.com/smartcontractkit/full-blockchain-solidity-course-py/discussions/1791

**Comment by emilrueh** [comment]
Ah, so you suggest switching to VRF V2 is a solution. Do you also think it solves the `Contract "Lottery" should be marked as abstract.` and the `Function has override specified but does not override anything.` issues?

**Comment by emilrueh** [comment]
Does that mean I change the imported code's virtual functions and add `override` to `fulfillRandomness()` in the imported contracts as well as the overriding function's declaration has to looks _exactly_ like the function to override?

Really appreciate the help btw.

**Comment by emilrueh** [comment]
I believe to have had all the things you mention already properly coded in my lottery contract and do not see where to start to fix the two abstract and override issues.

Please have a look into the below code snippet:
```
// SPDX-License-Identifier: MIT

pragma solidity ^0.6.6;
import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@chainlink/contracts/src/v0.6/VRFConsumerBase.sol";

contract Lottery is VRFConsumerBase, Ownable {
    address payable[] public players;
    address public recentWinner;
    uint256 public usdEntryFee;
    AggregatorV3Interface internal ethUsdPriceFeed;
    uint256 public fee;
    bytes32 public keyHash;

    enum LOTTERY_STATE {
        OPEN,
        CLOSED,
        CALCULATING_WINNER
    }

    LOTTERY_STATE public lottery_state;

    constructor(
        address _priceFeedAddress,
        address _vrfCoordinator,
        address _link,
        uint256 _fee,
        bytes32 _keyHash
    ) public VRFConsumerBase(_vrfCoordinator, _link) {
        fee = _fee;
        keyHash = _keyHash;
        lottery_state = LOTTERY_STATE.CLOSED;
        usdEntryFee = 50 * (10**18);
        ethUsdPriceFeed = AggregatorV3Interface(_priceFeedAddress);
    }

    function endLottery() public onlyOwner {
        lottery_state = LOTTERY_STATE.CALCULATING_WINNER;
        requestRandomness(keyHash, fee);
    }

    function fulfillRandomness(uint256 _requestId, bytes32 _randomness)
        internal
        override
    {
        // WINNER SELECTION
        uint256 indexOfWinner = uint256(_randomness) % players.length;
        recentWinner = players[indexOfWinner];
        payable(recentWinner).transfer(address(this).balance);
    }
}
```

**Comment by emilrueh** [comment]
Interesting, I have not yet learned about this comment writing but will look into it. Thanks again! :)
