### ISSUE TITLE
Lesson 11, code verification on etherscan

### ISSUE THREAD

**Issue by DieKant** [smartcontractkit/full-blockchain-solidity-course-py#312]
Hi @PatrickAlphaC , I can't understand why in the video/repo, when you write the deploy script for AdvancedCollectible contract, you don't use something like:

publish_source=config["networks"][network.show_active()].get("verify", False)

while deploying the contract, then your code is verified on etherscan rinkeby in the video(I did my scripts following yours and mine is not getting verified)
Did I miss something?

**Comment by PatrickAlphaC** [comment]
I made these videos and changed how I liked my projects setup a few times XD.

In your `brownie-config.yaml` you'll need a `verify: True` part for the network you want it to verify on.

Otherwise, you can just hardcode it to `publish_source=True`, just keep in mind this won't work on a local chain, or chain that doesn't have an etherscan integration.
