### ISSUE TITLE
Having trouble understanding how the "test_issue_token" passes

### ISSUE THREAD

**Issue by DieKant** [smartcontractkit/full-blockchain-solidity-course-py#446]
Hi @PatrickAlphaC 

What I'm not understanding about this test is:

The dapp token supply is 1000000
The staking reward for staking 1 eth should be 2000 dapp since or INITIAL_PRICE_FEED_VALUE is 2000

We call the issueToken function so that each staker can get their staking rewards, the function calls the transfer method on the dapp token contract to transfer the funds ............BUT in the deploy script we transfered almost the whole supply FROM the dapp token contract TO the token farm contract. 

This leaves the dapp token contract with only 100 tokens(which I think it's the KEPT_BALANCE constant) in it's balance and we have to transfer 2000 of them as reward

So how does the test passes? The dapp token contract should't have the neccessary funds to do that
Maybe I'm missing something

**Comment by cromewar** [comment]
Hello @DieKant you are right, this is something we do as a security measure, the transfer funds should be a `onlyOwner` function, otherwise anyone would have access to the contract on etherscan and transfer to their wallet any amount they want to. so we send almost the total supply to the wallet which deploys de contracts as that wallet becomes the Owner of the contract, it mean you would actually transfer from the Owner wallet to the staker wallet the funds.

This is something you could handle with a third party decentralized admin called Oracle.

**Comment by DieKant** [comment]
Hi @cromewar

Thank you for the answer, now I understand what is going on
