### ISSUE TITLE
Rinkeby insufficient funds for gas!

### ISSUE THREAD

**Issue by chuukwuemeka** [smartcontractkit/full-blockchain-solidity-course-py#603]
I couldn't get fund my account via the Rinkeby Faucet even tweeted post for test eth request

Getting an "insufficient funds for gas * price + value" error persists. 

0x34e2665a8DE0f39796B5c1AbD711BE155A28cA04
Please help so I can continue the course.

**Comment by B-Tanvir** [comment]
It is the same problem I encountered. However I think, you can continue with the course.

**Comment by chuukwuemeka** [comment]
How were you able to do the transactions?

**Comment by jethr0null** [comment]
@B-Tanvir You have a few options here: 

* Request ETH from the Chainlink Testnet [Faucet](https://faucets.chain.link/rinkeby) (select Rinkeby network and they will give you .1 ETH per request)
* Deploy using the JS VM or to a local blockchain instance (e.g. using Ganache) if you're not trying to interact with any contracts on the public blockchain. 
* Adjust the fund/gas amounts so that you are within the limit of your available ETH (if you have any)

Hope this helps. Good luck!
