### ISSUE TITLE
How getEntranceFee works?

### ISSUE THREAD

**Issue by kevinyou77** [smartcontractkit/full-blockchain-solidity-course-py#667]
So I've been following the tutorial for a bit and it's been fantastic. But I came across this piece of code

```
function getEntranceFee() public view returns (uint256) {
        uint256 minimumUSD = 50 * 10**18;
        uint256 price = getPrice();
        uint256 precision = 1 * 10**18;

        return (minimumUSD * precision) / price;
}
```

I couldn't quite understand why we have to use precision here. Can anyone explain it to me? It would be much appreciated if the logic is explained too. Thanks!

**Comment by cromewar** [comment]
Hello @kevinyou77  as you know the getPrice from chainlink returns a value based on the current price, but that number has an specific number of decimals, the reason we use precision is due to how the ERC20 tokens works,  they work with 18 decimals (1 eth is 1000000000000000000). So is a good practice to set all our numbers and amounts as that, and also when we setup our prices we do it on wei, so that's the reason.
